package pqcratchet

// kem.go implements a hybrid KEM combining ML-KEM-768 (FIPS 203) and X25519.
//
// Wire layout:
//
//	HybridKEMPublicKey  = MLKEMPublicKey (1184 B)  || X25519PublicKey (32 B)         = 1216 B
//	HybridKEMPrivateKey = MLKEMKeySeed (64 B)       || X25519PrivateScalar (32 B)    = 96 B
//	HybridKEMCiphertext = MLKEMCiphertext (1088 B)  || X25519EphemeralPublicKey (32 B) = 1120 B
//
// The ML-KEM private key is stored as its 64-byte seed (KeySeedSize) rather
// than the 2400-byte expanded private key. NewKeyFromSeed reconstructs the
// full key on each operation. This halves the private key storage and makes
// zeroing trivial.
//
// The X25519 component uses an ephemeral keypair per encapsulation; the
// encapsulator's ephemeral public key is sent inside the ciphertext and used
// for X25519 DH on the decapsulator side.
//
// Both shared secrets are combined via HKDF so security holds if either
// primitive is broken:
//
//	SS = HKDF(mlkem_ss || x25519_ss, salt=SHA256(recipientPub), info="pqcratchet/v1/HybridKEM")

import (
	cryptorand "crypto/rand"
	"crypto/sha256"
	"fmt"
	"io"

	mlkem768 "github.com/cloudflare/circl/kem/mlkem/mlkem768"
	"golang.org/x/crypto/curve25519"
	"golang.org/x/crypto/hkdf"
)

const (
	// MLKEMPublicKeySize is the ML-KEM-768 public key size (1184 bytes).
	MLKEMPublicKeySize = mlkem768.PublicKeySize // 1184

	// MLKEMKeySeedSize is the ML-KEM-768 key seed size (d || z = 64 bytes).
	// Private keys are stored as seeds for compact, zeroable storage.
	MLKEMKeySeedSize = mlkem768.KeySeedSize // 64

	// MLKEMCiphertextSize is the ML-KEM-768 ciphertext size (1088 bytes).
	MLKEMCiphertextSize = mlkem768.CiphertextSize // 1088

	// MLKEMEncapSeedSize is the randomness size for ML-KEM encapsulation (32 bytes).
	MLKEMEncapSeedSize = mlkem768.EncapsulationSeedSize // 32

	// X25519KeySize is the Curve25519 key/point size.
	X25519KeySize = 32

	// HybridPublicKeySize is MLKEMPublicKey || X25519PublicKey.
	HybridPublicKeySize = MLKEMPublicKeySize + X25519KeySize // 1216

	// HybridPrivateKeySize is MLKEMKeySeed || X25519PrivateScalar.
	HybridPrivateKeySize = MLKEMKeySeedSize + X25519KeySize // 96

	// HybridCiphertextSize is MLKEMCiphertext || X25519EphemeralPublicKey.
	HybridCiphertextSize = MLKEMCiphertextSize + X25519KeySize // 1120
)

// HybridKEMPublicKey is an encapsulation key.
// Layout: MLKEMPublicKey (1184 B) || X25519PublicKey (32 B)
type HybridKEMPublicKey [HybridPublicKeySize]byte

// HybridKEMPrivateKey is a decapsulation key (stored as seed).
// Layout: MLKEMKeySeed (64 B) || X25519PrivateScalar (32 B)
type HybridKEMPrivateKey [HybridPrivateKeySize]byte

// HybridKEMCiphertext is the encapsulation output.
// Layout: MLKEMCiphertext (1088 B) || X25519EphemeralPublicKey (32 B)
type HybridKEMCiphertext [HybridCiphertextSize]byte

// HybridKEMKeyPair holds a matched public/private key pair.
// Always use *HybridKEMKeyPair. Call ZeroKEMKeyPair when done.
type HybridKEMKeyPair struct {
	Public  HybridKEMPublicKey
	Private HybridKEMPrivateKey
}

// ZeroKEMKeyPair overwrites the private key material in kp with zeros.
// The public key is NOT zeroed — it is not secret, and zeroing it could
// mislead callers into treating a zeroed public key as valid.
func ZeroKEMKeyPair(kp *HybridKEMKeyPair) {
	if kp == nil {
		return
	}
	for i := range kp.Private {
		kp.Private[i] = 0
	}
}

// GenerateKEMKeyPair generates a fresh hybrid KEM keypair using r for
// randomness. If r is nil, crypto/rand.Reader is used.
//
// The ML-KEM key is generated by reading a 64-byte seed from r and passing it
// to NewKeyFromSeed. This gives the caller control over the entropy source
// (useful for deterministic tests) without bypassing the ML-KEM key derivation.
//
// X25519 private scalar clamping: per RFC 7748 §5, the X25519 function clamps
// the scalar by clearing bits 0, 1, 2 of byte 0, clearing bit 7 of byte 31,
// and setting bit 6 of byte 31. golang.org/x/crypto/curve25519 applies this
// clamping internally — callers do not need to pre-clamp the scalar.
//
//	[RFC 7748] https://www.rfc-editor.org/rfc/rfc7748
func GenerateKEMKeyPair(r io.Reader) (*HybridKEMKeyPair, error) {
	if r == nil {
		r = cryptorand.Reader
	}

	// ML-KEM-768: derive key pair from a random seed read from r.
	var seed [MLKEMKeySeedSize]byte
	if _, err := io.ReadFull(r, seed[:]); err != nil {
		return nil, fmt.Errorf("mlkem seed: %w", err)
	}
	mlkemPub, _ := mlkem768.NewKeyFromSeed(seed[:])
	// The private key is stored as the raw seed (64 bytes) rather than the
	// expanded 2400-byte form. NewKeyFromSeed reconstructs it on each operation.

	// X25519 keypair.
	var x25519Priv [X25519KeySize]byte
	if _, err := io.ReadFull(r, x25519Priv[:]); err != nil {
		return nil, fmt.Errorf("x25519 keygen: %w", err)
	}
	x25519Pub, err := curve25519.X25519(x25519Priv[:], curve25519.Basepoint)
	if err != nil {
		return nil, fmt.Errorf("x25519 pubkey: %w", err)
	}

	var kp HybridKEMKeyPair
	// Public: MLKEMPublicKey || X25519PublicKey
	var mlkemPubBytes [MLKEMPublicKeySize]byte
	mlkemPub.Pack(mlkemPubBytes[:])
	copy(kp.Public[:MLKEMPublicKeySize], mlkemPubBytes[:])
	copy(kp.Public[MLKEMPublicKeySize:], x25519Pub)
	// Private: MLKEMKeySeed (64 B) || X25519PrivateScalar (32 B)
	copy(kp.Private[:MLKEMKeySeedSize], seed[:])
	copy(kp.Private[MLKEMKeySeedSize:], x25519Priv[:])

	return &kp, nil
}

// Encapsulate produces a ciphertext and shared secret against pub.
// If r is nil, crypto/rand.Reader is used.
//
// The ML-KEM encapsulation seed and the X25519 ephemeral key are both read
// from r independently. Passing a deterministic reader (e.g. a fixed-seed PRNG)
// makes encapsulations deterministic: the same seed produces the same ciphertext
// and shared secret, which breaks IND-CCA2. Only pass a non-random reader
// in deterministic tests; production callers must use nil or crypto/rand.
//
// Low-order point rejection: curve25519.X25519 returns an error if the DH
// output is the all-zero point (which arises from low-order inputs per RFC 7748
// §6.1). This error is propagated, preventing a degenerate shared secret from
// entering the HKDF combiner.
//
//	[RFC 7748 §5]  https://www.rfc-editor.org/rfc/rfc7748#section-5
//	[RFC 7748 §6.1] https://www.rfc-editor.org/rfc/rfc7748#section-6.1
func Encapsulate(r io.Reader, pub *HybridKEMPublicKey) (*HybridKEMCiphertext, []byte, error) {
	if r == nil {
		r = cryptorand.Reader
	}

	// Parse ML-KEM public key.
	var mlkemPub mlkem768.PublicKey
	if err := mlkemPub.Unpack(pub[:MLKEMPublicKeySize]); err != nil {
		return nil, nil, fmt.Errorf("mlkem public key: %w", err)
	}

	// ML-KEM encapsulation with explicit seed for testability.
	// circl's EncapsulateTo panics on wrong sizes or nil seed (it falls
	// through to crypto/rand and panics if that fails). All three args are
	// sized to exact spec constants so this cannot panic in practice.
	var encapSeed [MLKEMEncapSeedSize]byte
	if _, err := io.ReadFull(r, encapSeed[:]); err != nil {
		return nil, nil, fmt.Errorf("mlkem encap seed: %w", err)
	}
	mlkemCT := make([]byte, MLKEMCiphertextSize)
	mlkemSS := make([]byte, mlkem768.SharedKeySize)
	mlkemPub.EncapsulateTo(mlkemCT, mlkemSS, encapSeed[:])

	// X25519 ephemeral encapsulation.
	var ephemeralPriv [X25519KeySize]byte
	if _, err := io.ReadFull(r, ephemeralPriv[:]); err != nil {
		return nil, nil, fmt.Errorf("x25519 ephemeral keygen: %w", err)
	}
	ephemeralPub, err := curve25519.X25519(ephemeralPriv[:], curve25519.Basepoint)
	if err != nil {
		return nil, nil, fmt.Errorf("x25519 ephemeral pubkey: %w", err)
	}
	x25519SS, err := curve25519.X25519(ephemeralPriv[:], pub[MLKEMPublicKeySize:])
	if err != nil {
		return nil, nil, fmt.Errorf("x25519 DH: %w", err)
	}

	var ct HybridKEMCiphertext
	copy(ct[:MLKEMCiphertextSize], mlkemCT)
	copy(ct[MLKEMCiphertextSize:], ephemeralPub)

	ss, err := combineKEMSecrets(mlkemSS, x25519SS, pub[:])
	if err != nil {
		return nil, nil, err
	}
	return &ct, ss, nil
}

// Decapsulate recovers the shared secret from ct using priv.
//
// The recipient private scalar is never transmitted; only the public key
// (reconstructed from the seed) leaves this function. curve25519.X25519
// clamps the scalar internally per RFC 7748 §5 and rejects the all-zero
// output per §6.1, propagating an error if a low-order input point is used.
//
//	[RFC 7748 §5]  https://www.rfc-editor.org/rfc/rfc7748#section-5
//	[RFC 7748 §6.1] https://www.rfc-editor.org/rfc/rfc7748#section-6.1
func Decapsulate(priv *HybridKEMPrivateKey, ct *HybridKEMCiphertext) ([]byte, error) {
	// Reconstruct ML-KEM key pair from seed.
	mlkemPub, mlkemPriv := mlkem768.NewKeyFromSeed(priv[:MLKEMKeySeedSize])

	// ML-KEM decapsulation.
	// circl's DecapsulateTo panics on wrong sizes rather than returning errors.
	// Both slices are sized to exact spec constants so this cannot panic.
	mlkemSS := make([]byte, mlkem768.SharedKeySize)
	mlkemPriv.DecapsulateTo(mlkemSS, ct[:MLKEMCiphertextSize])

	// X25519 decapsulation.
	recipientPriv := priv[MLKEMKeySeedSize:]
	x25519SS, err := curve25519.X25519(recipientPriv, ct[MLKEMCiphertextSize:])
	if err != nil {
		return nil, fmt.Errorf("x25519 DH: %w", err)
	}

	// Reconstruct the public key used as combineKEMSecrets context.
	// This must produce the same bytes the encapsulator used.
	var pub HybridKEMPublicKey
	var mlkemPubBytes [MLKEMPublicKeySize]byte
	mlkemPub.Pack(mlkemPubBytes[:])
	copy(pub[:MLKEMPublicKeySize], mlkemPubBytes[:])
	x25519Pub, err := curve25519.X25519(recipientPriv, curve25519.Basepoint)
	if err != nil {
		return nil, fmt.Errorf("x25519 pubkey: %w", err)
	}
	copy(pub[MLKEMPublicKeySize:], x25519Pub)

	return combineKEMSecrets(mlkemSS, x25519SS, pub[:])
}

// combineKEMSecrets derives a 32-byte combined shared secret via HKDF over
// mlkemSS || x25519SS.
//
// Salt design: SHA-256 of the recipient's full hybrid public key is used as
// the HKDF salt. This binds the combined secret to a specific recipient key
// pair and prevents cross-key confusion: without this binding, an adversary
// who can arrange for two different recipients to have related ML-KEM or X25519
// keys could potentially construct a combined secret that is the same for both,
// breaking the independence between sessions. Using the recipient's full public
// key as salt ensures that even if the two component shared secrets (mlkemSS
// and x25519SS) were somehow related across two different recipient keys, the
// HKDF output would differ because the salts differ.
//
// The salt is non-secret (public key is transmitted in plaintext) and is the
// same value on both the encapsulator and decapsulator sides because both
// reconstruct the recipient public key from the same material.
func combineKEMSecrets(mlkemSS, x25519SS, pubContext []byte) ([]byte, error) {
	// Concatenate the two shared secrets as HKDF input key material.
	// Use an explicit pre-allocated buffer rather than appending to mlkemSS,
	// so this is safe regardless of the allocation origin of mlkemSS.
	// Appending to mlkemSS directly would work today (cap==len from make()),
	// but would silently alias if mlkemSS ever had excess capacity.
	ikm := make([]byte, 0, len(mlkemSS)+len(x25519SS))
	ikm = append(ikm, mlkemSS...)
	ikm = append(ikm, x25519SS...)
	salt := sha256.Sum256(pubContext)
	// HKDF-SHA256 with non-zero salt (RFC 5869 §2.2). Both encapsulator and
	// decapsulator derive the same salt from the same public key bytes.
	// https://www.rfc-editor.org/rfc/rfc5869#section-2.2
	r := hkdf.New(sha256.New, ikm, salt[:], infoHybridKEM)
	ss := make([]byte, 32)
	if _, err := io.ReadFull(r, ss); err != nil {
		return nil, fmt.Errorf("hybrid KEM KDF: %w", err)
	}
	return ss, nil
}
